Reproducible Research - Week 2 Course Project
============================================

### Loading and preprocessing the data
```{r, warning=FALSE, tidy=TRUE, message=FALSE}
# 1 Load the data
data_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
temp <- tempfile()
download.file(data_url, temp)
unzip(temp, "activity.csv")
Raw_Data <- read.csv("activity.csv")


# 2 Process/transform the data into a format suitable for your analysis
library(dplyr)
Raw_df <- tbl_df(Raw_Data)
Clean_df <- filter(Raw_df, !is.na(steps))
```

### What is the mean total number of steps taken per day?
```{r, warning=FALSE, tidy=TRUE, message=FALSE}
# 1 Calculate the total number of steps taken per day?
Daily_df <- group_by(Clean_df,date)
Daily_df <- summarise(Daily_df,total_steps=sum(steps))
Daily_df <- ungroup(Daily_df)

# 2 If you do not understand the difference between a histogram and a barplot, research the difference between them. 
#   Make a histogram of the total number of steps taken each day
hist(Daily_df$total_steps, 
     col = "red", 
     breaks=20, 
     main = "Daily Steps Histogram", 
     xlab="Total Steps")

# 3 Calculate and report the mean and median of the total number of steps taken per day
summarise(Daily_df, Mean_Steps=mean(total_steps), Median_Steps=median(total_steps))
```

### What is the average daily activity pattern?
```{r, warning=FALSE, tidy=TRUE, message=FALSE}
# 1 Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, 
#   averaged across all days (y-axis)
library(ggplot2)
Interval_df <- group_by(Clean_df, interval)
Interval_df <- summarise(Interval_df,Avg_Steps=mean(steps))
Interval_df <- ungroup(Interval_df)

ggplot(Interval_df, aes(interval, Avg_Steps)) + geom_line() + xlab("Interval") + ylab("Avg Steps")

# 2 Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
max_step <- summarise(Interval_df,Max_Steps=max(Avg_Steps))
Interval_max <- filter(Interval_df, Avg_Steps==max_step$Max_Steps)
Interval_max
```

### Imputing missing values
```{r, warning=FALSE, tidy=TRUE, message=FALSE}
# 1 Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
Missing_df <- Raw_df[!complete.cases(Raw_df), ]
nrow(Missing_df)

# 2 Devise a strategy for filling in all of the missing values in the dataset. 
#   The strategy does not need to be sophisticated. 
#   For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc
impute_val <- summarise(Clean_df, Mean_Steps=mean(steps))
Imputed_df <- mutate(Raw_df, impute_steps = ifelse(is.na(steps), impute_val$Mean_Steps, steps))
Imputed_df

# 3 Create a new dataset that is equal to the original dataset but with the missing data filled in.
Imputed_df_orig <- mutate(Raw_df, steps = ifelse(is.na(steps), impute_val$Mean_Steps, steps))
Imputed_df_orig

# 4 Make a histogram of the total number of steps taken each day and calculate and report the mean and median total number 
#   of steps taken per day. Do these values differ from the estimates from the first part of the assignment? 
#   What is the impact of imputing missing data on the estimates of the total daily number of steps?
Daily_df_impute <- group_by(Imputed_df_orig,date)
Daily_df_impute <- summarise(Daily_df_impute,total_steps=sum(steps))
Daily_df_impute <- ungroup(Daily_df_impute)

hist(Daily_df_impute$total_steps, 
     col = "blue", 
     breaks=20, 
     main = "Daily Steps Histogram (Imputed)", 
     xlab="Total Steps")

summarise(Daily_df, Mean_Steps=mean(total_steps), Median_Steps=median(total_steps))
summarise(Daily_df_impute, Mean_Steps=mean(total_steps), Median_Steps=median(total_steps))
```

### Are there differences in activity patterns between weekdays and weekends?
```{r, warning=FALSE, tidy=TRUE, message=FALSE}
# 1 Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether 
#   a given date is a weekday or weekend day.
Imputed_df_orig <- mutate(Imputed_df_orig, weekday = weekdays(as.Date(date, '%Y-%m-%d'),abbreviate=TRUE))
Imputed_df_orig <- mutate(Imputed_df_orig, weekday_fct = ifelse(weekday=="Sat" | weekday=="Sun", "weekend","weekday"))
Imputed_df_orig$weekday_fct <- as.factor(Imputed_df_orig$weekday_fct)

# 2 Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) 
#   and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
#   See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
Interval_df2 <- group_by(Imputed_df_orig, weekday_fct, interval)
Interval_df2 <- summarise(Interval_df2,Avg_Steps=mean(steps))
Interval_df2 <- ungroup(Interval_df2)

my_plot <- ggplot(Interval_df2, aes(interval, Avg_Steps)) + geom_line() + xlab("Interval") + ylab("Avg Steps")
my_plot + facet_grid(. ~ weekday_fct)
```